services:
  postgres:
    image: postgres:16-alpine
    container_name: dental-clinic-db
    environment:
      POSTGRES_DB: dental_clinic
      POSTGRES_USER: ramadan
      POSTGRES_PASSWORD: ramadan1111
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ramadan -d dental_clinic"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dental-clinic-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DATABASE_URL: jdbc:postgresql://postgres:5432/dental_clinic
      DATABASE_USERNAME: ramadan
      DATABASE_PASSWORD: ramadan1111
      JWT_SECRET: ZGVudGFsLWNsaW5pYy1tYW5hZ2VtZW50LXN5c3RlbS1qd3Qtc2VjcmV0LWtleS0yMDI0LXByb2R1Y3Rpb24=
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      MAIL_FROM: ${MAIL_FROM:-noreply@dental-clinic.com}
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
