services:
  postgres:
    image: postgres:16-alpine
    container_name: dental-clinic-db
    environment:
      POSTGRES_DB: dental_clinic
      POSTGRES_USER: ramadan
      POSTGRES_PASSWORD: ramadan1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ramadan -d dental_clinic"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
